version = 1
SPDX-PackageName = "Send-Keys extension for Chocolatey (helper to send keystrokes to a window) (sendkeys.extension)"
SPDX-PackageDownloadLocation = "https://github.com/foundata/chocolatey-sendkeys.extension"
SPDX-PackageSupplier = "foundata GmbH <https://foundata.com>"
SPDX-PackageComment = """
This project may include calls to Application Programming Interfaces
("API calls"), as well as their respective specifications and code that
allows software to communicate with other software. API calls to products
or services developed outside of this project are not licensed under the
licensing or usage terms that govern this project. Any use of such API
calls and related external products is subject to applicable additional
agreements with their respective provider and does not alter, expand or
supersede any terms of these additional agreements.
"""

[[annotations]]
path = "**"
precedence = "closest"
SPDX-FileCopyrightText = "foundata GmbH <https://foundata.com>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "assets/images/cursor-default-click-outline.svg"
precedence = "closest"
SPDX-FileCopyrightText = "2022 Pictogrammers / Michael Irigoyen <https://pictogrammers.com/contributor/mririgoyen/>"
SPDX-License-Identifier = "Apache-2.0"
SPDX-FileComment = "https://pictogrammers.com/library/mdi/icon/cursor-default-click-outline/, https://pictogrammers.com/docs/general/license/"
